#!/usr/bin/env python3
# Copyright (c) 2025 Nations Technologies Inc.
# SPDX-License-Identifier: Apache-2.0

"""Request and show Y8 or hardware-JPEG frames from NSLink's CDC ACM port.

Refreshes a live window by default; pass --single to grab one frame and exit.
NSLink is selected by USB VID/PID: COMx in Windows, /dev/ttyACMx in Linux/WSL.
--port overrides detection; --list-ports shows the current runtime's devices.
USB/IP ownership must be switched outside this program before changing OS.
The view is shown at the received resolution unless --scale magnifies it.
The window is created once at that size and the program never resizes it again,
so it stays where you put it -- and drag it if you want it a different size.

The firmware keeps SDRAM disabled and can report person-detection metadata.
This client also supports builds without inference. --benchmark 100
measures received and decoded frames without opening a window. --jpeg on/off
selects hardware compression or raw Y8; JPEG is the default. Explicit auto
leaves the MCU mode alone. Unavailable inference never blocks image display.

Protocol, all little-endian:
  'OV56' | width:u16 | height:u16 | format:u32 | length:u32 | payload
format 1 is RGB565 and nothing else.  format 2 inserts a four-byte detection
record between the header and the payload -- person score:i8, no-person
score:i8, reserved, then flags (bit0 inference valid, bit1 the person class
won).  The record precedes the payload so the frame being received can be
annotated without waiting for the end of it.  Both scores are a two-class
softmax (scale 1/256, zero point -128), so either can be read as a probability.
Format 3 is a complete JPEG image generated by the N32H787 JPEG encoder; format
4 is JPEG plus the same four-byte detection record.  JPEG normally reduces the
wire time substantially. Formats 1/2 are retained for legacy RGB565 firmware.
Formats 5/6 are RGB565/JPEG with asynchronous inference: the four-byte detection
record is followed by preview frame ID, inference source frame ID, and source
age in milliseconds (three u32 values). The verdict is not for the live frame.
Formats 7/8 extend 5/6 with copy, preprocessing, and model Invoke microseconds
(three u32 values), measured on M7 for the same inference result.
Formats 9/10 carry raw Y8 (one byte per pixel), without metadata / with the
same timed metadata as format 8. Current firmware uses these for raw fallback
and emits a true single-component grayscale JPEG in formats 3/8.

Baud notes, measured on the N32H787_HMI_V1.1 board:
  * The MCU's USART1 is clocked at 300 MHz with no prescale, so it could reach
    18.75 Mbaud; the limit is the NSLink bridge, not the MCU.
  * The bridge takes its UART rate from this side's line coding, so --baud must
    match USER/src/n32h7xx_cfg.c or the link carries nothing at all.  Note that
    a mismatch is *silent*, not garbled, which makes it easy to blame the wrong
    end.
  * Earlier WSL tests: short exchanges survive rates that bulk transfer does not: a one-byte
    command round-trip still answers at 4 Mbaud, but sustained 38400-byte
    frames fail above ~1 Mbaud. The QVGA grayscale test at 921600 also lost
    payload chunks, so it is not a reliable bulk-transfer default.
The default is 921600: Windows native received 500/500 frames, whereas WSL
USB/IP lost payload bytes in 15/500 requests with the same firmware and baud.
A 10.3 KB frame takes ~112 ms on the 8N1 wire. JPEG size depends on the scene.
A 320x240 raw Y8 frame takes ~0.83 s;
raw previews are therefore substantially slower.

Legacy RGB565 byte order: 0x4300 = 0x6f emits the low byte first
and the default decode below assumes that.  Getting it backwards is subtle --
it scrambles R/G/B into each other rather than swapping two channels, so the
colour-bar test pattern still shows eight distinct saturated bars and the
capture looks plausible, while every real scene turns into rainbow contour
bands.  Verify byte order against the bar's *hues* (white, yellow, cyan, green,
magenta, red, blue, black), never against a count of distinct values.

Incomplete frames use a stall deadline to permit retrying. Missing bytes do
not by themselves identify whether the loss was in UART, the bridge or USB/IP.
Serial writes also have a deadline; flush/tcdrain is deliberately avoided.
"""
import argparse
from pathlib import Path
import queue
import struct
import sys
import threading
import time

import cv2
import numpy as np
import serial
from serial.tools import list_ports

SERIAL_OPEN_ERRORS = (serial.SerialException, OSError)
if sys.platform != "win32":
    import termios
    SERIAL_OPEN_ERRORS += (termios.error,)

MAGIC = b"OV56"
HEADER_SIZE = 16
RGB565 = 1
RGB565_WITH_DETECTION = 2
JPEG = 3
JPEG_WITH_DETECTION = 4
RGB565_ASYNC = 5
JPEG_ASYNC = 6
RGB565_TIMED = 7
JPEG_TIMED = 8
GRAY8 = 9
GRAY8_TIMED = 10
GRAY_FORMATS = (GRAY8, GRAY8_TIMED)
TIMED_FORMATS = (RGB565_TIMED, JPEG_TIMED, GRAY8_TIMED)
RAW_FORMATS = (RGB565, RGB565_WITH_DETECTION, RGB565_ASYNC, RGB565_TIMED)
JPEG_FORMATS = (JPEG, JPEG_WITH_DETECTION, JPEG_ASYNC, JPEG_TIMED)
ASYNC_FORMATS = (RGB565_ASYNC, JPEG_ASYNC) + TIMED_FORMATS
DETECTION_SIZE = 4
MAX_JPEG_SIZE = 96 * 1024
DEFAULT_BAUD = 921600
WRITE_TIMEOUT = 1.0
NSLINK_USB_ID = (0x19F5, 0x3106)


def port_ownership_hint():
    if sys.platform == "win32":
        return ("Windows Python needs a COM port owned by Windows. If NSLink is "
                "attached to WSL, check 'usbipd list' and run "
                "'usbipd detach --busid <BUSID>' in Windows first.")
    return ("Linux/WSL Python needs a /dev/ttyACM* or /dev/ttyUSB* port. "
            "On WSL, check 'usbipd list' and attach NSLink with "
            "'usbipd attach --wsl --busid <BUSID>' in Windows first.")


def describe_ports(ports):
    return "; ".join(f"{p.device} ({p.description or 'unknown'}, {p.hwid or 'no ID'})"
                     for p in ports) or "none"


def resolve_serial_port(requested=None):
    if requested and requested.lower() != "auto":
        if sys.platform == "win32" and requested.startswith("/dev/"):
            raise serial.SerialException("Windows Python cannot open a Linux device path; "
                                         "omit --port for auto-detection or use --port COMx.")
        if sys.platform != "win32" and requested.upper().startswith("COM") and requested[3:].isdigit():
            raise serial.SerialException("Linux Python cannot open a Windows COM name; "
                                         "omit --port for auto-detection. " + port_ownership_hint())
        return requested
    ports = sorted(list_ports.comports(), key=lambda p: p.device)
    matches = [p for p in ports if (p.vid, p.pid) == NSLINK_USB_ID]
    if not matches:
        matches = [p for p in ports if "nslink" in
                   " ".join(filter(None, (p.description, p.product, p.manufacturer))).lower()]
    if len(matches) == 1:
        return matches[0].device
    if len(matches) > 1:
        raise serial.SerialException("Multiple NSLink serial ports found; choose --port: "
                                     + describe_ports(matches))
    raise serial.SerialException("No NSLink serial port detected. Available: "
                                 + describe_ports(ports) + ". " + port_ownership_hint()
                                 + " Other adapters require an explicit --port.")


def open_camera_port(device, baud):
    options = dict(timeout=0.2, write_timeout=WRITE_TIMEOUT)
    if sys.platform != "win32":
        options["exclusive"] = True
    try:
        return serial.Serial(device, baud, **options)
    except SERIAL_OPEN_ERRORS as exc:
        raise serial.SerialException(f"Cannot open {device} at {baud} baud: {exc}. "
                                     + port_ownership_hint()) from exc

# Windows this run has already created and sized, so show_frame sizes each once.
_SIZED_WINDOWS = set()

# The MCU's two-class softmax: scale 1/256, zero point -128, so a score s is a
# probability of (s + 128) / 256.
def score_to_probability(score):
    return (score + 128) / 256.0


def annotate(display, detection, scale):
    """Draw the person-detector verdict onto a decoded frame, in place.

    A green border and a label mean the "person" class won; grey means it did
    not.  Drawing on the BGR array rather than into the RGB565 stream keeps the
    pixels the sensor actually produced intact, so a snapshot still shows the
    real frame.
    """
    person, no_person, flags = detection[:3]
    found = bool(flags & 2)
    colour = (0, 200, 0) if found else (150, 150, 150)
    if found:
        label = "PERSON %d%%" % round(score_to_probability(person) * 100)
    else:
        label = "none %d%%" % round(score_to_probability(no_person) * 100)
    if len(detection) >= 6:
        label += f" (async #{detection[4]}, {detection[5] / 1000:.1f}s old)"

    height, width = display.shape[:2]
    cv2.rectangle(display, (0, 0), (width - 1, height - 1), colour,
                  1 if width < 480 else 2)
    compact = width < 480
    cv2.putText(display, label, (3, height - 4),
                cv2.FONT_HERSHEY_SIMPLEX, 0.3 if compact else 0.6,
                colour, 1 if compact else 2, cv2.LINE_AA)
    return found, label


def read_exact(port, size, stall_s=0.4, start_s=4.0):
    """Read exactly `size` bytes, giving up quickly once the stream stops.

    The deadlines are deliberately split.  A frame arrives as one continuous
    burst, so `start_s` only has to cover the wait before the first byte; after
    that, any gap longer than `stall_s` means the rest of this frame is not
    coming. A stalled stream should be retried rather than blocking the viewer.

    `start_s` is four seconds rather than one because the MCU answers 'C' from
    its own capture loop: the reply can be delayed by a whole person-detection
    cycle, which is ~1.5 s of inference.  Once bytes start arriving the link,
    not the model, sets the pace.  Pass a shorter value when the detector is
    known to be off, where a cycle is ~50 ms.
    """
    result = bytearray()
    deadline = time.monotonic() + start_s
    while len(result) < size:
        data = port.read(size - len(result))
        if data:
            result.extend(data)
            deadline = time.monotonic() + stall_s
        elif time.monotonic() >= deadline:
            raise TimeoutError(f"only received {len(result)}/{size} bytes")
    return bytes(result)


def read_frame(port, timing=None):
    """Fetch one frame: (width, height, pixel_format, payload, detection).

    `pixel_format` identifies raw Y8, legacy RGB565, or JPEG plus metadata.
    The detection record sits between the header and payload, so the verdict is
    known before image bytes arrive.
    """
    started = time.monotonic() if timing is not None else 0.0
    port.reset_input_buffer()
    port.write(b"C")
    # A reply implies the command was transmitted. tcdrain/flush can hang on
    # a stalled USB/IP CDC endpoint even when write_timeout is configured.
    window = bytearray()
    deadline = time.monotonic() + 4.0
    while True:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise TimeoutError("no OV56 frame header within 4 seconds")
        window.extend(read_exact(port, 1, start_s=remaining))
        if len(window) > len(MAGIC):
            del window[0]
        if bytes(window) == MAGIC:
            break
    header_at = time.monotonic() if timing is not None else 0.0
    rest = read_exact(port, HEADER_SIZE - len(MAGIC))
    width, height, pixel_format, length = struct.unpack("<HHII", rest)
    if pixel_format not in RAW_FORMATS + GRAY_FORMATS + JPEG_FORMATS:
        raise ValueError(f"unexpected frame: {width}x{height}, "
                         f"format={pixel_format}, bytes={length}")
    if pixel_format in RAW_FORMATS and length != width * height * 2:
        raise ValueError(f"unexpected frame: {width}x{height}, "
                         f"format={pixel_format}, bytes={length}")
    if pixel_format in GRAY_FORMATS and length != width * height:
        raise ValueError(f"Invalid Y8 frame: {width}x{height}, bytes={length}")
    if pixel_format in JPEG_FORMATS and not 4 <= length <= MAX_JPEG_SIZE:
        raise ValueError(f"unexpected JPEG: {width}x{height}, bytes={length}")
    detection = None
    if pixel_format in (RGB565_WITH_DETECTION, JPEG_WITH_DETECTION) + ASYNC_FORMATS:
        person, no_person, _reserved, flags = read_exact(port, DETECTION_SIZE)
        detection = (person - 256 if person > 127 else person,
                     no_person - 256 if no_person > 127 else no_person,
                     flags)
        if pixel_format in ASYNC_FORMATS:
            detection += struct.unpack("<III", read_exact(port, 12))
        if pixel_format in TIMED_FORMATS:
            detection += struct.unpack("<III", read_exact(port, 12))
    payload = read_exact(port, length)
    if timing is not None:
        finished = time.monotonic()
        timing.update(request_to_header=header_at - started,
                      header_to_payload=finished - header_at,
                      receive=finished - started)
    if pixel_format in JPEG_FORMATS and (
            payload[:2] != b"\xff\xd8" or payload[-2:] != b"\xff\xd9"):
        raise ValueError("JPEG payload has no SOI/EOI markers")
    return width, height, pixel_format, payload, detection


def rgb565_to_bgr(raw, width, height, swap_bytes=False):
    """Decode RGB565, low byte first as the sensor emits it.

    The MCU programs 0x4300 = 0x6f, which Linux's OV5640 driver documents as
    {g[2:0],b[4:0]} then {r[4:0],g[5:3]} -- low byte first.  Decoding that
    backwards does not merely swap red and blue: every output channel becomes a
    mixture of bits from different real channels, so a one-step change in a
    smooth gradient lands far away in the result and flat areas break into
    rainbow contour bands.  A colour bar survives it (still eight distinct flat
    regions), which is how a byte-swapped decode can pass a glance test while
    every real scene looks wrong.  Pass swap_bytes only if a capture decodes to
    the wrong hues while the bars stay saturated.
    """
    pixels = np.frombuffer(raw, dtype=np.uint8).reshape(height, width, 2)
    if swap_bytes:
        value = (pixels[:, :, 0].astype(np.uint16) << 8) | pixels[:, :, 1]
    else:
        value = (pixels[:, :, 1].astype(np.uint16) << 8) | pixels[:, :, 0]
    red = ((value >> 11) & 0x1F) * 255 // 31
    green = ((value >> 5) & 0x3F) * 255 // 63
    blue = (value & 0x1F) * 255 // 31
    return np.dstack((blue, green, red)).astype(np.uint8)


def decode_frame(pixel_format, payload, width, height, swap_bytes=False):
    if pixel_format in GRAY_FORMATS:
        gray = np.frombuffer(payload, dtype=np.uint8).reshape(height, width)
        return cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
    if pixel_format in RAW_FORMATS:
        return rgb565_to_bgr(payload, width, height, swap_bytes)
    image = cv2.imdecode(np.frombuffer(payload, dtype=np.uint8), cv2.IMREAD_COLOR)
    if image is None or image.shape[:2] != (height, width):
        raise ValueError("OpenCV could not decode the received JPEG")
    return image


def set_person_detection(port, want_on):
    """Send 'N' until the MCU confirms the detector is in the asked-for state.

    Called on every run, in both directions, rather than only for --no-person.
    The detector's state lives in MCU RAM and 'N' toggles it, so it is not a
    property of this program: a previous --no-person run leaves it off, and the
    next plain run would then classify nothing while the operator waits for a
    green box that is never coming.  Opening the port usually resets the MCU,
    which would restore the power-on default, but that is not dependable -- a
    reset swallows a command that arrives while the MCU is still booting, and
    at least one run was observed not to reset at all.  Asking and confirming
    costs a byte and a short reply, so pinning the state beats assuming it.

    The reply is what decides whether to send again: silence means the byte was
    lost and another is worth trying, and the opposite state means the toggle
    landed on the wrong side and one more 'N' settles it.  A one-byte command
    and a short reply ride out link rates that bulk frame transfer does not, so
    this is safe to do before the frames start flowing.
    """
    wanted = b"person-on" if want_on else b"person-off"
    opposite = b"person-off" if want_on else b"person-on"

    time.sleep(1.0)
    deadline = time.monotonic() + 10.0
    while time.monotonic() < deadline:
        port.reset_input_buffer()
        port.write(b"N")
        seen = bytearray()
        reply_deadline = time.monotonic() + 3.0
        while time.monotonic() < reply_deadline:
            try:
                chunk = port.read(64)
            except serial.SerialException:
                break
            if not chunk:
                continue
            seen.extend(chunk)
            if (b"person-off" in seen or b"person-on" in seen
                    or b"person-unavailable" in seen or b"person-disabled" in seen):
                break
        if b"person-unavailable" in seen or b"person-disabled" in seen:
            print("MCU person detector is disabled/unavailable; receiving without inference",
                  flush=True)
            return
        if wanted in seen:
            print(f"MCU reports {wanted.decode()}")
            return
        # Silent, or the opposite state: send 'N' again.
        if opposite in seen:
            time.sleep(0.05)

    print("could not confirm the person detector is "
          f"{'on' if want_on else 'off'}; it may be the other way round")


def show_frame(window, image):
    """Show a frame in a window whose size the program fixes once and leaves.

    Plain cv2.imshow ties the window to the image: a new window is created at
    the image's size, and any later image of a different size resizes it again.
    So the window jumps whenever the frame dimensions change -- a --scale
    change, or any future sensor mode.  Creating the window with WINDOW_NORMAL
    decouples the two: the frame is scaled into whatever size the window
    already has, and from then on only a drag from the user moves it.
    """
    if window not in _SIZED_WINDOWS:
        cv2.namedWindow(window, cv2.WINDOW_NORMAL)
        cv2.resizeWindow(window, image.shape[1], image.shape[0])
        _SIZED_WINDOWS.add(window)
    cv2.imshow(window, image)


def preview_with_status(image, fps, pixel_format, payload_size, dropped, detection=None):
    """Append a readable status strip without drawing on camera pixels."""
    height, width = image.shape[:2]
    canvas_width = max(width, 320)
    display = np.full((height + 140, canvas_width, 3), 28, dtype=np.uint8)
    left = (canvas_width - width) // 2
    display[:height, left:left + width] = image
    encoding = ("JPEG" if pixel_format in JPEG_FORMATS else
                "Y8" if pixel_format in GRAY_FORMATS else "RGB565")
    cv2.putText(display, f"{fps:.1f} FPS  |  {encoding}",
                (10, height + 25), cv2.FONT_HERSHEY_SIMPLEX,
                0.6, (235, 235, 235), 1, cv2.LINE_AA)
    cv2.putText(display, f"{payload_size / 1024:.1f} KiB  |  dropped {dropped}",
                (10, height + 50), cv2.FONT_HERSHEY_SIMPLEX,
                0.45, (180, 180, 180), 1, cv2.LINE_AA)
    label = "Person: --"
    colour = (180, 180, 180)
    if detection is not None and detection[2] & 1:
        person, no_person, flags = detection[:3]
        label = (f"P {score_to_probability(person):.0%}  "
                 f"No {score_to_probability(no_person):.0%}  "
                 f"{'PERSON' if flags & 2 else 'none'}")
        if flags & 2:
            colour = (80, 220, 120)
        if len(detection) >= 6:
            label = (f"Async {'PERSON' if flags & 2 else 'none'} "
                     f"{score_to_probability(person if flags & 2 else no_person):.0%} "
                     f"| {detection[5] / 1000:.1f}s old")
    elif detection is not None and len(detection) >= 6:
        label = "Person: waiting for M7"
    cv2.putText(display, label, (10, height + 76), cv2.FONT_HERSHEY_SIMPLEX,
                0.5, colour, 1, cv2.LINE_AA)
    if detection is not None and len(detection) == 9 and detection[2] & 1:
        copy_us, prep_us, invoke_us = detection[6:9]
        for offset, text in (
                (101, f"M7 infer {invoke_us / 1000:.2f} ms"),
                (126, f"prep {prep_us / 1000:.2f} | copy {copy_us / 1000:.2f} ms")):
            size, _ = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, .45, 1)
            font_scale = .45 * min(1.0, (canvas_width - 20) / max(1, size[0]))
            cv2.putText(display, text, (10, height + offset), cv2.FONT_HERSHEY_SIMPLEX,
                        font_scale, (200, 200, 200), 1, cv2.LINE_AA)
    return display


def inference_timing_text(detection):
    if detection is None or len(detection) != 9 or not detection[2] & 1:
        return None
    copy_us, prep_us, invoke_us = detection[6:9]
    return (f"M7 frame={detection[4]} infer={invoke_us / 1000:.3f} ms "
            f"preprocess={prep_us / 1000:.3f} ms copy={copy_us / 1000:.3f} ms")


def save_snapshot(payload, image, raw_path, pixel_format):
    if raw_path is None:
        suffix = (".jpg" if pixel_format in JPEG_FORMATS else
                  ".y8" if pixel_format in GRAY_FORMATS else ".rgb565")
        raw_path = f"ov5640_{image.shape[1]}x{image.shape[0]}" + suffix
    with open(raw_path, "wb") as output:
        output.write(payload)
    preview_path = str(Path(raw_path).with_suffix(".preview.png"))
    cv2.imwrite(preview_path, image)
    print(f"saved {raw_path} and {preview_path}")


def set_jpeg_mode(port, mode):
    """The firmware's J command toggles and acknowledges its new state."""
    if mode == "auto":
        return
    wanted = b"jpeg-" + mode.encode()
    for _ in range(2):
        port.reset_input_buffer()
        port.write(b"J")
        reply = bytearray()
        deadline = time.monotonic() + 4.0
        while time.monotonic() < deadline:
            reply.extend(port.read(64))
            if b"\n" in reply:
                break
        if wanted in reply:
            print(wanted.decode(), flush=True)
            return
        if b"jpeg-on" not in reply and b"jpeg-off" not in reply:
            raise RuntimeError(f"JPEG mode was not acknowledged: {bytes(reply)!r}")
    raise RuntimeError("could not set JPEG mode")


def profile_command(port, command, prefix):
    port.reset_input_buffer()
    port.write(command)
    line = bytearray()
    deadline = time.monotonic() + 5.0
    while time.monotonic() < deadline:
        line.extend(port.read(1))
        if line.endswith(b"\n"):
            text = line.decode("ascii", errors="replace").strip()
            if text.startswith(prefix):
                return text
            line.clear()
        if len(line) > 1024:
            raise ValueError("oversized profiling response")
    raise TimeoutError("no profiling response; flash firmware with G/H support")


def capture_benchmark(port, frames, swap_bytes=False, profile=False):
    """Count bounded requests, validating every received image including JPEG."""
    sizes, latencies, formats = [], [], set()
    inference_times = {}
    errors = 0
    stage_times = []
    if profile:
        print(profile_command(port, b"G", "PROFILE-START"), flush=True)
    started = time.monotonic()
    for index in range(frames):
        frame_started = time.monotonic()
        try:
            timing = {}
            if profile:
                width, height, fmt, payload, detection = read_frame(port, timing=timing)
            else:
                width, height, fmt, payload, detection = read_frame(port)
            decode_started = time.monotonic()
            decode_frame(fmt, payload, width, height, swap_bytes)
            if profile:
                timing["decode"] = time.monotonic() - decode_started
                stage_times.append(timing)
        except (TimeoutError, ValueError) as exc:
            errors += 1
            print(f"frame {index + 1}: {exc}", flush=True)
            continue
        sizes.append(len(payload))
        latencies.append(time.monotonic() - frame_started)
        formats.add(fmt)
        if inference_timing_text(detection) is not None:
            inference_times[detection[4]] = detection[6:9]
    elapsed = time.monotonic() - started
    print(f"received {len(sizes)}/{frames} frames in {elapsed:.3f}s: "
          f"{len(sizes) / elapsed:.2f} fps, {errors} failed", flush=True)
    if sizes:
        print(f"formats={sorted(formats)}; payload bytes min/mean/max="
              f"{min(sizes)}/{sum(sizes) / len(sizes):.1f}/{max(sizes)}; "
              f"request+decode ms min/mean/max={1000 * min(latencies):.2f}/"
              f"{1000 * sum(latencies) / len(latencies):.2f}/"
              f"{1000 * max(latencies):.2f}", flush=True)
    if inference_times:
        timings = list(inference_times.values())
        print(f"M7 unique results observed={len(timings)}; " + "; ".join(
            f"{name} ms min/mean/max="
            f"{min(t[i] for t in timings) / 1000:.3f}/"
            f"{sum(t[i] for t in timings) / len(timings) / 1000:.3f}/"
            f"{max(t[i] for t in timings) / 1000:.3f}"
            for i, name in enumerate(("copy", "preprocess", "invoke"))), flush=True)
    if profile:
        print(profile_command(port, b"H", "PROFILE "), flush=True)
        if stage_times:
            print("HOST " + "; ".join(
                f"{key} ms min/mean/max="
                f"{min(t[key] for t in stage_times) * 1000:.3f}/"
                f"{sum(t[key] for t in stage_times) / len(stage_times) * 1000:.3f}/"
                f"{max(t[key] for t in stage_times) * 1000:.3f}"
                for key in ("request_to_header", "header_to_payload", "receive", "decode")),
                flush=True)
    return len(sizes), errors


def capture_live(port, args):
    """Refresh a window while a worker thread keeps the link busy.

    Acquisition cannot share a thread with the GUI.  Reading one frame blocks
    for ~0.47 s and recovering a dropped one for ~0.4 s more, and this build's
    only GUI backend is Qt5 under WSLg, where a main thread parked in a serial
    read neither repaints the window nor sees the keyboard -- so the window
    looks hung even while frames arrive perfectly.  The worker therefore owns
    the port, the main thread owns OpenCV and blocks on a queue instead, and
    the display keeps its own cadence whatever the link is doing.
    """
    window = "OV5640 live (q/Esc quit, s snapshot)"
    incoming = queue.Queue(maxsize=2)
    stop = threading.Event()
    stats = {"frames": 0, "drops": 0, "error": None, "fatal": None,
             "bytes": 0, "person_frames": 0,
             "last_label": None}

    def reader():
        while not stop.is_set():
            try:
                item = read_frame(port)
            except (TimeoutError, ValueError) as exc:
                # Recoverable: read_frame drops the rest of the broken frame
                # and resynchronises on the magic on its next call.
                stats["drops"] += 1
                stats["error"] = str(exc)
                time.sleep(0.05)
                continue
            except serial.SerialException as exc:
                stats["fatal"] = str(exc)
                stop.set()
                return
            # Hand the frame over without ever blocking.  A reader that pauses
            # stops draining the port, and the bridge starts dropping packets
            # the moment the read side falls behind, so a stale frame is
            # discarded here rather than making the reader wait.
            try:
                incoming.put_nowait(item)
            except queue.Full:
                try:
                    incoming.get_nowait()
                except queue.Empty:
                    pass
                try:
                    incoming.put_nowait(item)
                except queue.Full:
                    pass

    worker = threading.Thread(target=reader, daemon=True)
    worker.start()

    latest_payload = None
    latest_format = None
    latest_image = None
    latest_display = None
    latest_detection = None
    fps = 0.0
    started = time.monotonic()
    last_report = started
    last_report_frames = 0
    try:
        while not stop.is_set():
            try:
                # Short enough that Qt events are pumped several times between
                # arrivals; this is the loop's only blocking call in GUI mode.
                width, height, latest_format, latest_payload, latest_detection = \
                    incoming.get(timeout=0.02)
                latest_image = decode_frame(latest_format, latest_payload,
                                            width, height, args.swap_bytes)
                stats["frames"] += 1
                stats["bytes"] += len(latest_payload)
                if latest_detection is not None and latest_detection[2] & 2:
                    stats["person_frames"] += 1
                if not args.no_show:
                    latest_display = cv2.resize(
                        latest_image,
                        (width * args.scale, height * args.scale),
                        interpolation=cv2.INTER_NEAREST)
            except queue.Empty:
                pass
            except ValueError as exc:
                stats["drops"] += 1
                stats["error"] = str(exc)
                latest_display = None
                latest_payload = None

            now = time.monotonic()
            if now - last_report >= 1.0:
                fps = (stats["frames"] - last_report_frames) / (now - last_report)
                last_report_frames = stats["frames"]
                last_report = now
                timing = inference_timing_text(latest_detection)
                if timing is not None and timing != stats["last_label"]:
                    print(timing, flush=True)
                    stats["last_label"] = timing
                if stats["error"] is not None:
                    print(f"frame error: {stats['error']} "
                          f"({stats['drops']} dropped so far)", flush=True)
                    stats["error"] = None
                if args.no_show:
                    print(f"{fps:.2f} fps ({stats['frames']} frames, "
                          f"format={latest_format}, "
                          f"{stats['bytes'] / max(1, stats['frames']):.0f} bytes/frame, "
                          f"{stats['drops']} dropped, "
                          f"{stats['person_frames']} with a person"
                          ")", flush=True)

            if args.no_show:
                continue

            if latest_display is not None:
                show_frame(window, preview_with_status(
                    latest_display, fps, latest_format, len(latest_payload),
                    stats["drops"], latest_detection))

            # Polled every pass, so the window stays responsive even while no
            # frame is arriving.  That is the point of the worker thread.
            key = cv2.waitKey(1) & 0xFF
            if key in (ord("q"), 27):
                break
            if key == ord("s") and latest_payload is not None:
                save_snapshot(latest_payload, latest_image, args.raw, latest_format)
    finally:
        stop.set()
        worker.join(timeout=5.0)

    elapsed = time.monotonic() - started
    print(f"stopped after {stats['frames']} frames in {elapsed:.1f}s "
          f"({stats['frames'] / elapsed:.2f} fps, {stats['drops']} dropped)")
    if not args.no_show:
        cv2.destroyAllWindows()
    if stats["fatal"]:
        raise serial.SerialException(stats["fatal"])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", default="auto",
                        help="auto-detect NSLink (default), or specify COMx / /dev/ttyACMx")
    parser.add_argument("--list-ports", action="store_true",
                        help="list serial ports visible to this Python runtime and exit")
    parser.add_argument("--baud", type=int, default=DEFAULT_BAUD)
    parser.add_argument("--swap-bytes", action="store_true",
                        help="decode high byte first; the default is low byte first, "
                             "which is what the sensor's 0x4300=0x6f emits")
    parser.add_argument("--raw", help="snapshot path; extension defaults to received format")
    parser.add_argument("--benchmark", type=int, metavar="FRAMES",
                        help="receive and decode this many frames, print throughput, exit")
    parser.add_argument("--profile", action="store_true",
                        help="include MCU stage timings and host receive/decode timings with --benchmark")
    parser.add_argument("--jpeg", choices=("auto", "on", "off"), default="on",
                        help="JPEG by default; off selects raw Y8, auto keeps MCU mode")
    parser.add_argument("--no-show", action="store_true", help="save files but do not open a GUI window")
    parser.add_argument("--single", action="store_true",
                        help="grab one frame and exit instead of refreshing live")
    parser.add_argument("--scale", type=int, default=2,
                        help="display magnification (default 2)")
    parser.add_argument("--no-person", action="store_true",
                        help="disable inference on firmware that supports it")
    args = parser.parse_args()
    if args.list_ports:
        print(f"Python platform: {sys.platform}")
        print(describe_ports(sorted(list_ports.comports(), key=lambda p: p.device)))
        print(port_ownership_hint())
        return
    if args.benchmark is not None and args.benchmark < 1:
        parser.error("--benchmark must be positive")
    if args.profile and args.benchmark is None:
        parser.error("--profile requires --benchmark")
    args.port = resolve_serial_port(args.port)
    print(f"Serial: {args.port} at {args.baud} baud ({sys.platform})", flush=True)

    # The detector is on by default, so the state is pinned on every run rather
    # than left to whatever the last run set -- see set_person_detection.
    want_person = not args.no_person

    if not args.single or args.benchmark is not None:
        with open_camera_port(args.port, args.baud) as port:
            set_person_detection(port, want_person)
            set_jpeg_mode(port, args.jpeg)
            if args.benchmark is not None:
                capture_benchmark(port, args.benchmark, args.swap_bytes, profile=args.profile)
            else:
                capture_live(port, args)
        return

    with open_camera_port(args.port, args.baud) as port:
        set_person_detection(port, want_person)
        set_jpeg_mode(port, args.jpeg)
        # Retry incomplete or malformed frames in single-shot mode.
        for attempt in range(4):
            try:
                width, height, pixel_format, raw, detection = read_frame(port)
                break
            except (TimeoutError, ValueError) as exc:
                if attempt == 3:
                    raise
                print(f"retrying after frame error: {exc}")
    image = decode_frame(pixel_format, raw, width, height, args.swap_bytes)
    if detection is not None:
        person, no_person, flags = detection[:3]
        print(f"person detector: person={person} ({score_to_probability(person):.1%})"
              f" no_person={no_person} ({score_to_probability(no_person):.1%})"
              f" -> {'PERSON' if flags & 2 else 'no person'}")
        if len(detection) >= 6:
            print(f"async: preview frame={detection[3]}, inference source="
                  f"{detection[4]}, source age={detection[5]} ms, valid={bool(flags & 1)}")
        timing = inference_timing_text(detection)
        if timing is not None:
            print(timing)
    save_snapshot(raw, image, args.raw, pixel_format)
    if args.no_show:
        return
    display = cv2.resize(image, (width * args.scale, height * args.scale),
                         interpolation=cv2.INTER_NEAREST)
    if detection is not None:
        annotate(display, detection, args.scale)
    show_frame(f"OV5640 {width}x{height} format={pixel_format}", display)
    print("press q or Esc to quit")
    while True:
        if cv2.waitKey(20) & 0xFF in (ord("q"), 27):
            break
    cv2.destroyAllWindows()


if __name__ == "__main__":
    try:
        main()
    except serial.SerialException as exc:
        raise SystemExit(f"Serial link failed: {exc}. Check port ownership and "
                         "the NSLink USB/IP connection; this is not a JPEG decode error.") from exc
    except KeyboardInterrupt:
        pass
